esphome:
  name: led-controller
  friendly_name: led-controller

esp8266:
  board: esp01_1m
  restore_from_flash: true

logger:

api:
  encryption:
    key: "your_secret_here"

ota:
  password: "your_secret_here"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Uncomment these and remove the neopixelbus below if you want to control a dumb led strip
# output:
#   - platform: esp8266_pwm
#     pin: GPIO13
#     frequency: 1000 Hz
#     id: pwm_output

# light:
#   - platform: monochromatic
#     id: light
#     output: pwm_output
#     name: LED Controller Lights

light:
  - platform: neopixelbus
    id: light
    name: LED Controller Lights
    variant: WS2811
    pin: GPIO13
    num_leds: 150
    default_transition_length: 0.5s
    restore_mode: RESTORE_DEFAULT_ON

# Uncomment this if you put a rotary encoder on your board
# sensor:
#   - platform: rotary_encoder
#     id: dimmer
#     internal: true
#     pin_a:
#       number: GPIO5
#       mode:
#         input: true
#         pullup: true
#     pin_b:
#       number: GPIO12
#       mode:
#         input: true
#         pullup: true
#     on_clockwise:
#       then:
#         - light.dim_relative:
#             id: light
#             relative_brightness: 10%
#             transition_length: 0.1s
#     on_anticlockwise:
#       then:
#         - light.dim_relative:
#             id: light
#             relative_brightness: -10%
#             transition_length: 0.1s

binary_sensor:
  - platform: gpio
    id: button_press
    internal: true
    filters:
      invert:
    pin:
      number: GPIO4
      mode:
        input: true
        pullup: true
    on_press:
      then:
        - light.toggle: light
